# Generated by Django 4.2 on 2026-01-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='amazon_link',
            field=models.URLField(blank=True, help_text='Amazon purchase link for related book', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='book_title',
            field=models.CharField(blank=True, help_text='Title of the related book', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='flipkart_link',
            field=models.URLField(blank=True, help_text='Flipkart purchase link for related book', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='meesho_link',
            field=models.URLField(blank=True, help_text='Meesho purchase link for related book', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'हिंदी (Hindi)'), ('ta', 'தமிழ் (Tamil)'), ('te', 'తెలుగు (Telugu)'), ('bn', 'বাংলা (Bengali)'), ('mr', 'मराठी (Marathi)'), ('gu', 'ગુજરાતી (Gujarati)'), ('kn', 'ಕನ್ನಡ (Kannada)'), ('ml', 'മലയാളം (Malayalam)'), ('pa', 'ਪੰਜਾਬੀ (Punjabi)')], default='en', help_text='Preferred language for the interface', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode')], default='light', help_text='Preferred theme (light or dark mode)', max_length=10),
        ),
    ]
