# Generated by Django 4.2.23 on 2026-02-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_article_amazon_link_article_book_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
