# Generated by Django 4.2 on 2026-02-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_otpverification_attempts_alter_otpverification_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_font_size',
        ),
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('HI', 'हिंदी (Hindi)'), ('TA', 'தமிழ் (Tamil)'), ('ML', 'മലയാളം (Malayalam)')], db_index=True, default='EN', help_text='Article language', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('EN', 'English'), ('HI', 'हिंदी (Hindi)'), ('TA', 'தமிழ் (Tamil)'), ('ML', 'മലയാളം (Malayalam)')], default='EN', help_text='Preferred language for reading articles', max_length=2),
        ),
    ]
