# Generated by Django 4.2 on 2026-03-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0008_readinglist_access_pin_readinglistaccessattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglistaccessattempt',
            name='delete_failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readinglistaccessattempt',
            name='delete_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
