#!/usr/bin/env python
"""
Interactive setup script for email configuration
Helps users configure Gmail SMTP for OTP sending
"""
import os
import re

def get_input(prompt, default=None):
    """Get user input with optional default"""
    if default:
        response = input(f"{prompt} [{default}]: ").strip()
        return response if response else default
    return input(f"{prompt}: ").strip()

def validate_email(email):
    """Validate email format"""
    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    return re.match(pattern, email) is not None

def validate_app_password(password):
    """Validate Gmail app password format"""
    # Remove spaces
    password = password.replace(' ', '')
    # Should be 16 characters, alphanumeric
    return len(password) == 16 and password.isalnum()

print("\n" + "="*70)
print("📧 SMARTREADER EMAIL SETUP - Configure Gmail for OTP Sending")
print("="*70)

print("\n📋 This wizard will help you configure email for OTP sending.")
print("   You'll need a Gmail account and App Password.\n")

# Step 1: Choose mode
print("Step 1: Choose Email Mode")
print("-" * 40)
print("1. Console Mode (Development) - OTP printed to terminal")
print("2. Real Email Mode (Production) - OTP sent to user's email")

mode = get_input("\nSelect mode (1 or 2)", "2")

if mode == "1":
    # Console mode
    print("\n✓ Console mode selected")
    print("  OTPs will be printed to the server terminal")
    print("  Good for development and testing\n")
    
    use_real_email = "False"
    email_host_user = "tamilanzzz001@gmail.com"
    email_host_password = "WAITING_FOR_APP_PASSWORD"
    
else:
    # Real email mode
    print("\n✓ Real Email mode selected")
    print("  OTPs will be sent to user's actual email addresses\n")
    
    use_real_email = "True"
    
    # Step 2: Get Gmail account
    print("\nStep 2: Gmail Account Configuration")
    print("-" * 40)
    print("Enter the Gmail address you want to use for sending OTPs.")
    print("Example: sriakilkaviraj2005@gmail.com\n")
    
    while True:
        email_host_user = get_input("Gmail address", "sriakilkaviraj2005@gmail.com")
        if validate_email(email_host_user):
            break
        print("❌ Invalid email format. Please try again.")
    
    print(f"✓ Email: {email_host_user}")
    
    # Step 3: Get App Password
    print("\nStep 3: Gmail App Password")
    print("-" * 40)
    print("You need a Gmail App Password (NOT your regular password).")
    print("\nTo get an App Password:")
    print("  1. Visit: https://myaccount.google.com/apppasswords")
    print("  2. Sign in with your Gmail account")
    print("  3. Make sure 2-Step Verification is enabled")
    print("  4. Create new App Password for 'SmartReader'")
    print("  5. Copy the 16-character password")
    print("\nExample: abcd efgh ijkl mnop (will be saved as: abcdefghijklmnop)")
    
    print("\n⚠️  IMPORTANT:")
    print("  - Use App Password, NOT your regular Gmail password")
    print("  - App Password is 16 characters")
    print("  - Spaces will be automatically removed")
    
    while True:
        email_host_password = get_input("\nGmail App Password (16 chars)")
        email_host_password = email_host_password.replace(' ', '')
        
        if validate_app_password(email_host_password):
            break
        print("❌ Invalid App Password. Must be 16 characters (spaces ignored).")
        print("   Example: abcdefghijklmnop")
    
    print(f"✓ App Password: {'*' * 16} (saved securely)")

# Step 4: Create/Update .env file
print("\n\nStep 4: Updating Configuration")
print("-" * 40)

env_path = os.path.join(os.path.dirname(__file__), '.env')

env_content = f"""# Django Settings
SECRET_KEY=7an=(s2w*e5)9=xu_$nyn2mi)ylg7hgs0f@qwjdug^(v9upcs8
DEBUG=True

# ============================================
# EMAIL CONFIGURATION FOR OTP SENDING
# ============================================
# Generated by setup_email_config.py on {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
#
# MODE: {'REAL EMAIL SENDING' if use_real_email == 'True' else 'CONSOLE MODE (Development)'}
#
# To change configuration later:
# - Run: python setup_email_config.py
# - Or manually edit this .env file
# - Then restart Django server

USE_REAL_EMAIL={use_real_email}
EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
EMAIL_HOST=smtp.gmail.com
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER={email_host_user}
EMAIL_HOST_PASSWORD={email_host_password}
DEFAULT_FROM_EMAIL=SmartReader <{email_host_user}>

# Database (SQLite by default)
DB_ENGINE=django.db.backends.sqlite3
DB_NAME=db.sqlite3
"""

try:
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print(f"✅ Configuration saved to: {env_path}")
    
except Exception as e:
    print(f"❌ Error saving configuration: {e}")
    print("\n📋 Manual Configuration:")
    print("   Copy the following to your .env file:\n")
    print(env_content)
    exit(1)

# Step 5: Test configuration
print("\n\nStep 5: Testing Email Configuration")
print("-" * 40)

if use_real_email == "True":
    test = get_input("Would you like to send a test email now? (y/n)", "y")
    
    if test.lower() == 'y':
        print("\n🔄 Testing email configuration...")
        print("   This will send a test OTP to: sriakilkaviraj2005@gmail.com")
        
        confirm = get_input("\nProceed with test? (y/n)", "y")
        
        if confirm.lower() == 'y':
            print("\n📧 Running test script...")
            print("   (This may take 5-10 seconds)\n")
            os.system('python test_otp_real_email.py')
        else:
            print("\n⏭️  Test skipped. You can run it later with:")
            print("   python test_otp_real_email.py")
    else:
        print("\n⏭️  Test skipped. You can run it later with:")
        print("   python test_otp_real_email.py")
else:
    print("\n✓ Console mode enabled - no email test needed")
    print("  OTPs will be printed to terminal during signup")

# Final instructions
print("\n\n" + "="*70)
print("🎉 EMAIL CONFIGURATION COMPLETE!")
print("="*70)

print("\n📋 Next Steps:")
print("   1. Restart Django development server")
print("   2. Go to signup page: http://127.0.0.1:8000/register/")
print("   3. Enter email: sriakilkaviraj2005@gmail.com")
print("   4. Click 'Send OTP' button")

if use_real_email == "True":
    print("   5. Check email inbox (and spam folder)")
    print("   6. OTP should arrive within 5-10 seconds!")
else:
    print("   5. Check the server terminal/console")
    print("   6. OTP will be printed there")

print("\n💡 Troubleshooting:")
print("   - If OTP not received, check spam/junk folder")
print("   - Run test script: python test_otp_real_email.py")
print("   - Check server console for error messages")
print("   - Read: SETUP_EMAIL_FOR_OTP.md")

print("\n✅ Your final year project is now ready for OTP-based signup!")
print("="*70 + "\n")
